### ISSUE TITLE
can i get latest version one & any plan for material design label:"help wanted" author:mrholek 

### ISSUE THREAD

**Issue by sambanthar** [mrholek/SimpliQ-Bootstrap-4-Admin-Template-with-AngularJS-Angular-2-support#1]

**Comment by sambanthar** [comment]
no response

**Comment by xidedix** [comment]
hi @sambanthar 
Our apologies for not getting back to you about your question. 
We're focused on Bootstrap 4 final release. 
Yes, there are plans for Material, it's going to be separate project, without Bootstrap dependency. 
At the moment it's hard to tell when it will happen.

**Comment by sambanthar** [comment]
hi @xidedix,
    no need of apologies. i just need to close it.that is why i put a message. sorry those words hurt you.
